[project]
name = "aiogram-bot-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "aerich==0.9.1",
  "aiofiles==24.1.0",
  "aiogram==3.22.0",
  "aiogram-dialog==2.4.0",
  "asyncpg==0.30.0",
  "betterlogging==1.0.0",
  "python-dotenv==1.1.1",
  "pytz==2025.2",
  "redis==6.2.0",
  "tortoise-orm==0.25.1",
]


[tool.aerich]
tortoise_orm = "app.database.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."
